/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as ApiCitiesRouteImport } from './routes/api/cities'
import { Route as ApiCitySlugRouteImport } from './routes/api/city/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitiesRoute = ApiCitiesRouteImport.update({
  id: '/api/cities',
  path: '/api/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitySlugRoute = ApiCitySlugRouteImport.update({
  id: '/api/city/$slug',
  path: '/api/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cities': typeof ApiCitiesRoute
  '/city/$slug': typeof CitySlugRoute
  '/api/city/$slug': typeof ApiCitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cities': typeof ApiCitiesRoute
  '/city/$slug': typeof CitySlugRoute
  '/api/city/$slug': typeof ApiCitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cities': typeof ApiCitiesRoute
  '/city/$slug': typeof CitySlugRoute
  '/api/city/$slug': typeof ApiCitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cities'
    | '/city/$slug'
    | '/api/city/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cities'
    | '/city/$slug'
    | '/api/city/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/explore'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cities'
    | '/city/$slug'
    | '/api/city/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCitiesRoute: typeof ApiCitiesRoute
  CitySlugRoute: typeof CitySlugRoute
  ApiCitySlugRoute: typeof ApiCitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cities': {
      id: '/api/cities'
      path: '/api/cities'
      fullPath: '/api/cities'
      preLoaderRoute: typeof ApiCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/city/$slug': {
      id: '/api/city/$slug'
      path: '/api/city/$slug'
      fullPath: '/api/city/$slug'
      preLoaderRoute: typeof ApiCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCitiesRoute: ApiCitiesRoute,
  CitySlugRoute: CitySlugRoute,
  ApiCitySlugRoute: ApiCitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
